services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    env_file: .env
    depends_on:
      - postgres
      - selenium
    networks:
      - appnet
  

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - appnet

  nginx:
    image: nginx:latest
    platform: linux/arm64
    container_name: nginx
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/frontend.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - default
  
  selenium:
    image: selenium/standalone-chrome:4.11.0-20230801
    container_name: selenium
    environment:
      - VNC_PASSWORD=chrome
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: '2gb'
  
  postgres:
    container_name: postgres
    image: postgres:18
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5332:5432"
    restart: unless-stopped
    networks:
      - appnet

  networks:
    appnet:

  volumes:
    postgres_data: