server {
    listen 8080;
    server_name localhost;

    access_log /var/log/nginx/access.log;

    # =========================
    # Django Admin + API
    # =========================
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /test.css {
        alias /app/staticfiles/admin/css/base.css;
    }

    location = /whoami {
        return 200 "THIS_IS_NGINX";
    }

    location /admin/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # =========================
    # Django Static (admin CSS/JS)
    # =========================
    location /static/admin/css/base.css {
        alias /app/staticfiles/admin/css/base.css;
    }
    
    location ^~ /static/ {
        alias /app/staticfiles/;
        autoindex on;
        access_log off;
        expires 1d;
    }

    location ^~ /media/ {
        alias /app/media/;
        autoindex on;
        access_log off;
        expires 1d;
    }



    # =========================
    # Frontend (Vue)
    # =========================
    location / {
        proxy_pass http://frontend:5173/;
        proxy_set_header Host $host;

        # 🔥 REQUIRED for Vite HMR (hot reload)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}