# Generated by Django 4.2.19 on 2026-04-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0002_movie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
