# Generated by Django 4.2.19 on 2026-04-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0003_alter_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cities',
            field=models.ManyToManyField(blank=True, to='cinemas.theater'),
        ),
    ]
