# Generated by Django 4.2.19 on 2026-06-30 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0004_movie_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTheater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemas.movie')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemas.theater')),
            ],
            options={
                'unique_together': {('movie', 'theater')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='theaters',
            field=models.ManyToManyField(blank=True, related_name='movies', through='cinemas.MovieTheater', to='cinemas.theater'),
        ),
    ]
