# Generated by Django 4.2.19 on 2026-06-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0005_movietheater_movie_theaters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cities',
        ),
    ]
